### ISSUE TITLE
Dockerizing POT, setting up error

### ISSUE THREAD

**Issue by auzias** [rflamary/POT#4]
By dockerizing POT using this [POT Dockerfile](https://gist.github.com/auzias/d62bd014cd47cd674aad7b2509400224) I came across an error that occurs during the command `python3 setup.py install --user`:

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named 'packaging'
```

Any idea how to solve this?

---
**Update**
I worked out first error but encounter another one. It seems related with Shippable/support#3316: the cause may be due to a new version of `setuptools`.

**Comment by rflamary** [comment]
Hello, has this problem been solved?

**Comment by ncourty** [comment]
closing this from our side as its not a POT issue.
